### ISSUE TITLE
Support Fortuneo

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/finance-toolkit#3]
- [x] Create pipeline for Fortuneo and recognize Fortuneo account (#1)
- [x] Append new transactions into existing transactions (#2)
- [x] Ensure the pipeline is runnable (#4)
- [x] Add integration test for Fortuneo (#4)
- [x] Support auto-completion for metadata (type, category, regularity) (#5)
